# Generated by Django 4.2.28 on 2026-04-24 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(unique=True, verbose_name='クレデンシャルID')),
                ('public_key', models.BinaryField(verbose_name='公開鍵')),
                ('sign_count', models.IntegerField(default=0, verbose_name='署名カウント')),
                ('name', models.CharField(default='マイデバイス', max_length=100, verbose_name='デバイス名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'パスキー',
                'verbose_name_plural': 'パスキー',
                'db_table': 'mfa_webauthn_credential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='TOTP秘密鍵')),
                ('confirmed', models.BooleanField(default=False, help_text='QRコード読み取り後に6桁コードで検証済みかどうか', verbose_name='設定完了')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='設定日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'TOTPデバイス',
                'verbose_name_plural': 'TOTPデバイス',
                'db_table': 'mfa_totp_device',
            },
        ),
    ]
