# Generated by Django 4.2.28 on 2026-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='secret',
            field=models.CharField(max_length=256, verbose_name='TOTP秘密鍵（暗号化済み）'),
        ),
    ]
