# Generated by Django 4.2.28 on 2026-03-02 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_remaining_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='取引先名')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='役職')),
                ('contact_person', models.CharField(blank=True, max_length=64, verbose_name='担当者')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('cc_email', models.TextField(blank=True, help_text='複数指定する場合はカンマ区切りで入力', verbose_name='CCメールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
            ],
            options={
                'verbose_name': '請求先',
                'verbose_name_plural': '請求先',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='請求日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='支払期日')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='件名')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('ISSUED', '発行済'), ('SENT', '送付済'), ('PAID', '入金済')], default='DRAFT', max_length=10, verbose_name='ステータス')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='billing/invoices/', verbose_name='PDFファイル')),
                ('drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='DriveファイルID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.companyinfo', verbose_name='自社情報')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='billing.billingcustomer', verbose_name='請求先')),
            ],
            options={
                'verbose_name': '売上請求書',
                'verbose_name_plural': '売上請求書',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('unit_price', models.IntegerField(default=0, verbose_name='単価')),
                ('unit', models.CharField(default='式', max_length=20, verbose_name='単位')),
                ('tax_category', models.CharField(choices=[('10', '10%'), ('8', '8%（軽減税率）'), ('0', '非課税')], default='10', max_length=2, verbose_name='税区分')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='品名')),
                ('unit_price', models.IntegerField(default=0, verbose_name='単価')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='式', max_length=20, verbose_name='単位')),
                ('tax_category', models.CharField(choices=[('10', '10%'), ('8', '8%（軽減税率）'), ('0', '非課税')], default='10', max_length=2, verbose_name='税区分')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.billinginvoice', verbose_name='請求書')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
