# Generated by Django 4.2.28 on 2026-03-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='billingitem',
            name='man_month',
            field=models.DecimalField(choices=[('0.25', '0.25'), ('0.50', '0.50'), ('0.75', '0.75'), ('1.00', '1.00')], decimal_places=2, default=1, max_digits=4, verbose_name='人月'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='商品選択で自動入力、手入力も可', max_length=30, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='billingproduct',
            name='name',
            field=models.CharField(max_length=30, verbose_name='商品名'),
        ),
    ]
