# Generated by Django 4.2.28 on 2026-03-18 14:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_status_alter_workreport_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, verbose_name='案件名')),
                ('start_date', models.DateField(verbose_name='契約開始日')),
                ('end_date', models.DateField(verbose_name='契約終了日')),
                ('billing_timing', models.CharField(choices=[('FIRST_DAY', '月初'), ('10TH_DAY', '10日'), ('15TH_DAY', '15日'), ('20TH_DAY', '20日'), ('LAST_DAY', '月末')], default='LAST_DAY', max_length=20, verbose_name='請求タイミング')),
                ('payment_terms', models.CharField(blank=True, default='毎月末日締め翌月末日払い', max_length=255, verbose_name='支払条件')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='billing.billingcustomer', verbose_name='取引先')),
            ],
            options={
                'verbose_name': 'クライアント基本契約',
                'verbose_name_plural': 'クライアント基本契約',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, help_text='クライアントが発番した注文番号', max_length=50, verbose_name='注文番号')),
                ('target_month', models.DateField(help_text='YYYY-MM-01形式', verbose_name='対象月')),
                ('work_start', models.DateField(verbose_name='作業開始日')),
                ('work_end', models.DateField(verbose_name='作業終了日')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='業務名称')),
                ('order_file', models.FileField(blank=True, help_text='クライアントから受領した注文書PDF', null=True, upload_to='received_orders/', verbose_name='注文書PDF')),
                ('parsed_data', models.JSONField(blank=True, help_text='PDFから自動抽出されたデータ', null=True, verbose_name='パース結果')),
                ('status', models.CharField(choices=[('REGISTERED', '登録済'), ('ACTIVE', '進行中'), ('COMPLETED', '完了'), ('CANCELLED', '取消')], default='REGISTERED', max_length=20, verbose_name='ステータス')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='注文日')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to='billing.clientcontract', verbose_name='基本契約')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to='billing.billingcustomer', verbose_name='取引先')),
            ],
            options={
                'verbose_name': '受注',
                'verbose_name_plural': '受注',
                'ordering': ['-target_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=64, verbose_name='要員名')),
                ('unit_price', models.IntegerField(default=0, verbose_name='単価')),
                ('man_month', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='人月')),
                ('time_lower_limit', models.DecimalField(decimal_places=2, default=140.0, max_digits=5, verbose_name='基準時間_下限')),
                ('time_upper_limit', models.DecimalField(decimal_places=2, default=180.0, max_digits=5, verbose_name='基準時間_上限')),
                ('shortage_rate', models.IntegerField(default=0, verbose_name='控除単価')),
                ('excess_rate', models.IntegerField(default=0, verbose_name='超過単価')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.receivedorder', verbose_name='受注')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '受注明細',
                'verbose_name_plural': '受注明細',
            },
        ),
        migrations.CreateModel(
            name='StaffTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=64, verbose_name='作業者名')),
                ('worker_type', models.CharField(choices=[('INTERNAL', '自社社員'), ('PARTNER', 'パートナー')], default='INTERNAL', max_length=10, verbose_name='要員種別')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='合計稼働時間')),
                ('work_days', models.IntegerField(default=0, verbose_name='稼働日数')),
                ('daily_data', models.JSONField(blank=True, help_text='[{"date": "2026-03-01", "hours": 8.0, "start": "9:00", "end": "18:00"}, ...]', null=True, verbose_name='日別データ')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('SUBMITTED', '提出済'), ('APPROVED', '承認済')], default='DRAFT', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='billing.receivedorder', verbose_name='受注')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='billing.receivedorderitem', verbose_name='受注明細')),
                ('partner_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_timesheets', to='invoices.workreport', verbose_name='パートナー稼働報告')),
            ],
            options={
                'verbose_name': '勤怠報告',
                'verbose_name_plural': '勤怠報告',
                'ordering': ['-target_month'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='入金日')),
                ('amount', models.IntegerField(verbose_name='入金額')),
                ('method', models.CharField(choices=[('TRANSFER', '銀行振込'), ('CHECK', '小切手'), ('OTHER', 'その他')], default='TRANSFER', max_length=10, verbose_name='入金方法')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='振込名義/備考')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='確認日時')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billinginvoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '入金記録',
                'verbose_name_plural': '入金記録',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='received_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='billing.receivedorder', verbose_name='受注'),
        ),
    ]
