# Generated by Django 4.2.28 on 2026-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billingitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='man_month',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='人月'),
        ),
    ]
