# Generated by Django 4.2.28 on 2026-03-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_clientcontract_receivedorder_receivedorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedorder',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='毎月自動でロールフォワードする注文', verbose_name='継続注文'),
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='ロールフォワード元の注文', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='billing.receivedorder', verbose_name='元注文'),
        ),
    ]
