# Generated by Django 4.2.28 on 2026-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_recurring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedorder',
            name='report_cc_emails',
            field=models.TextField(blank=True, help_text='カンマ区切りで複数指定可（例: a@example.com, b@example.com）', verbose_name='報告書CC'),
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='report_to_email',
            field=models.EmailField(blank=True, help_text='作業報告書の送信先メールアドレス', max_length=254, verbose_name='報告書送信先(TO)'),
        ),
    ]
