# Generated by Django 4.2.28 on 2026-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_report_email_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafftimesheet',
            options={'ordering': ['-target_month'], 'verbose_name': '稼働報告', 'verbose_name_plural': '稼働報告'},
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='invoice_cc_emails',
            field=models.TextField(blank=True, help_text='カンマ区切りで複数指定可', verbose_name='請求書CC'),
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='invoice_to_email',
            field=models.EmailField(blank=True, help_text='請求書の送信先メールアドレス', max_length=254, verbose_name='請求書送信先(TO)'),
        ),
    ]
