# Generated by Django 4.2.28 on 2026-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_invoice_email_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcustomer',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所2'),
        ),
        migrations.AddField(
            model_name='receivedorderitem',
            name='settlement_middle_hours',
            field=models.DecimalField(decimal_places=2, default=170.0, help_text='中間割の場合の基準時間', max_digits=5, verbose_name='中間基準時間'),
        ),
        migrations.AddField(
            model_name='receivedorderitem',
            name='settlement_type',
            field=models.CharField(choices=[('MIDDLE', '中間割'), ('RANGE', '上下限割')], default='RANGE', max_length=10, verbose_name='精算条件'),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所1'),
        ),
    ]
