# Generated by Django 4.2.28 on 2026-03-28 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_timesheet_excel_and_sent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='PayrollSystemの社員番号と一致', max_length=20, unique=True, verbose_name='社員番号')),
                ('name', models.CharField(max_length=64, verbose_name='氏名')),
                ('name_kana', models.CharField(blank=True, max_length=128, verbose_name='フリガナ')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終同期日時')),
            ],
            options={
                'verbose_name': '同期社員',
                'verbose_name_plural': '同期社員',
                'ordering': ['employee_id'],
            },
        ),
        migrations.AddField(
            model_name='stafftimesheet',
            name='employee_id',
            field=models.CharField(blank=True, help_text='PayrollSystemの社員番号。自社社員の場合に設定', max_length=20, verbose_name='社員番号'),
        ),
    ]
