# Generated by Django 4.2.29 on 2026-04-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_synced_employee_and_timesheet_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimesheet',
            name='holiday_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='休日の稼働時間', max_digits=6, verbose_name='休日出勤時間'),
        ),
        migrations.AddField(
            model_name='stafftimesheet',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='22:00〜5:00の深夜労働時間', max_digits=6, verbose_name='深夜残業時間'),
        ),
        migrations.AddField(
            model_name='stafftimesheet',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='月間の残業時間（通常残業）', max_digits=6, verbose_name='残業時間'),
        ),
    ]
