# Generated by Django 4.2.29 on 2026-04-29 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_timesheet_overtime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftimesheet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='billing.receivedorder', verbose_name='受注'),
        ),
    ]
