# Generated by Django 4.2.29 on 2026-04-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_make_timesheet_order_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimesheet',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='自動生成された稼働報告PDFファイル', null=True, upload_to='timesheets/pdf/', verbose_name='PDFファイル'),
        ),
    ]
