# Generated by Django 4.2.29 on 2026-04-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_pdf_file_to_stafftimesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcustomer',
            name='report_email',
            field=models.TextField(blank=True, help_text='稼働報告書の送付先。複数指定する場合はカンマ区切りで入力', verbose_name='報告書送付先メール'),
        ),
    ]
