# Generated by Django 4.2.29 on 2026-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_report_email_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftimesheet',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='DriveファイルID'),
        ),
    ]
