# Generated by Django 4.2.29 on 2026-04-30 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_paymentterm_closing_day_paymentterm_payment_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0013_add_drive_file_id_to_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedorder',
            name='partner_order',
            field=models.ForeignKey(blank=True, help_text='対応するパートナーへの発注', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to='orders.order', verbose_name='パートナー発注'),
        ),
        migrations.CreateModel(
            name='MonthlyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('INTERNAL', '自社社員'), ('PARTNER', 'パートナー')], default='INTERNAL', max_length=10, verbose_name='報告種別')),
                ('worker_name', models.CharField(max_length=128, verbose_name='作業者名')),
                ('worker_type', models.CharField(choices=[('INTERNAL', '自社社員'), ('PARTNER', 'パートナー')], default='INTERNAL', max_length=10, verbose_name='要員種別')),
                ('employee_id', models.CharField(blank=True, help_text='PayrollSystemの社員番号。自社社員の場合に設定', max_length=20, verbose_name='社員番号')),
                ('target_month', models.DateField(help_text='常にYYYY-MM-01形式', verbose_name='対象月')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('UPLOADED', '受領済'), ('PARSED', '解析済'), ('ALERT', '要確認'), ('SUBMITTED', '提出済'), ('APPROVED', '承認済'), ('SENT', '送付済'), ('ERROR', 'エラー')], default='DRAFT', max_length=10, verbose_name='ステータス')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='合計稼働時間')),
                ('work_days', models.IntegerField(default=0, verbose_name='稼働日数')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='残業時間')),
                ('night_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='深夜残業時間')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='休日出勤時間')),
                ('daily_data', models.JSONField(blank=True, null=True, verbose_name='日別データ')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='timesheets/excel/', verbose_name='Excelファイル')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='timesheets/pdf/', verbose_name='PDFファイル')),
                ('original_filename', models.CharField(blank=True, max_length=512, verbose_name='元ファイル名')),
                ('drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='DriveファイルID')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='アップロード日時')),
                ('alerts_json', models.JSONField(blank=True, null=True, verbose_name='警告データ')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True, verbose_name='クライアント送付日時')),
                ('client_shared_url', models.URLField(blank=True, max_length=500, verbose_name='共有URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_timesheets', to='orders.order', verbose_name='パートナー発注')),
                ('received_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_timesheets', to='billing.receivedorder', verbose_name='クライアント受注')),
                ('received_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_timesheets', to='billing.receivedorderitem', verbose_name='受注明細')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '月次稼働報告',
                'verbose_name_plural': '月次稼働報告',
                'ordering': ['-target_month', 'worker_name'],
            },
        ),
    ]
