# Generated by Django 4.2.29 on 2026-04-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_add_monthly_timesheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffTimesheet',
        ),
    ]
