# Generated by Django 4.2.28 on 2026-03-12 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='有限会社 マックプランニング', max_length=128, verbose_name='社名')),
                ('postal_code', models.CharField(default='116-0012', max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(default='東京都荒川区東尾久8-9-14', max_length=255, verbose_name='住所')),
                ('tel', models.CharField(default='090-3043-0477', max_length=20, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='FAX番号')),
                ('representative_title', models.CharField(default='代表取締役', max_length=64, verbose_name='代表者役職')),
                ('representative_name', models.CharField(default='吉川 裕', max_length=64, verbose_name='代表者名')),
                ('registration_no', models.CharField(default='TXXXXXXXXXXXXX', max_length=20, verbose_name='登録番号')),
                ('responsible_person', models.CharField(default='吉川 裕', max_length=64, verbose_name='委託業務責任者')),
                ('contact_person', models.CharField(default='吉川 裕', max_length=64, verbose_name='連絡窓口担当者')),
                ('bank_name', models.CharField(blank=True, max_length=64, verbose_name='銀行名')),
                ('bank_branch', models.CharField(blank=True, max_length=64, verbose_name='支店名')),
                ('account_type', models.CharField(choices=[('普通', '普通'), ('当座', '当座')], default='普通', max_length=20, verbose_name='口座種別')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='口座番号')),
                ('account_name', models.CharField(blank=True, max_length=128, verbose_name='口座名義')),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name='印影画像')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='ロゴ画像')),
            ],
            options={
                'verbose_name': '自社情報',
                'verbose_name_plural': '自社情報',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='会社名')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('representative_title', models.CharField(blank=True, default='代表取締役', max_length=64, verbose_name='代表者役職')),
                ('representative_name', models.CharField(blank=True, max_length=64, verbose_name='代表者名')),
                ('registration_no', models.CharField(blank=True, help_text='T13桁の番号', max_length=20, verbose_name='登録番号')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': '取引先',
                'verbose_name_plural': '取引先',
                'db_table': 'core_client',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='システム内で識別するためのコード', max_length=50, unique=True, verbose_name='テンプレートコード')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.TextField(help_text='Djangoテンプレート構文が使用可能です。例: {{ partner_name }}', verbose_name='本文')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='説明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メールテンプレート',
                'verbose_name_plural': 'メールテンプレート',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='会社名')),
                ('name_kana', models.CharField(blank=True, max_length=255, verbose_name='会社名（フリガナ）')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='FAX番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('cc', models.TextField(blank=True, help_text='複数指定する場合はカンマ区切りで入力してください', verbose_name='Cc')),
                ('bcc', models.TextField(blank=True, help_text='複数指定する場合はカンマ区切りで入力してください', verbose_name='Bcc')),
                ('representative_name', models.CharField(blank=True, max_length=64, verbose_name='代表者名')),
                ('representative_name_kana', models.CharField(blank=True, max_length=128, verbose_name='代表者名（フリガナ）')),
                ('representative_position', models.CharField(blank=True, max_length=64, verbose_name='代表者役職')),
                ('responsible_person', models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者')),
                ('contact_person', models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者')),
                ('registration_no', models.CharField(blank=True, help_text='T13桁の番号', max_length=20, verbose_name='登録番号')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='customers/attachments/', verbose_name='添付書類（決算報告書等）')),
                ('bank_name', models.CharField(blank=True, max_length=64, verbose_name='銀行名')),
                ('bank_branch', models.CharField(blank=True, max_length=64, verbose_name='支店名')),
                ('account_type', models.CharField(choices=[('普通', '普通'), ('当座', '当座')], default='普通', max_length=20, verbose_name='口座種別')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='口座番号')),
                ('account_name', models.CharField(blank=True, max_length=128, verbose_name='口座名義')),
                ('staff_contact', models.ForeignKey(blank=True, help_text='契約承認時の通知メール送信先となるスタッフ', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partners', to=settings.AUTH_USER_MODEL, verbose_name='自社担当者')),
            ],
            options={
                'verbose_name': 'パートナー',
                'verbose_name_plural': 'パートナー',
                'db_table': 'core_customer',
            },
        ),
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.TextField(verbose_name='本文')),
                ('recipient', models.EmailField(blank=True, help_text='送信先メールアドレス', max_length=254, verbose_name='送信先')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.partner', verbose_name='パートナー')),
            ],
            options={
                'verbose_name': 'メール送信ログ',
                'verbose_name_plural': 'メール送信ログ',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_login', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='パートナー')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
        migrations.CreateModel(
            name='MasterContractProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', '招待済み'), ('INFO_DONE', '基本情報登録済み'), ('CONTRACT_SENT', '基本契約送信済み'), ('PENDING_APPROVAL', '承認待ち'), ('COMPLETED', '締結完了')], default='INVITED', max_length=20, verbose_name='ステータス')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='契約書PDF')),
                ('pdf_hash', models.CharField(blank=True, help_text='SHA256ハッシュ値（電帳法対応）', max_length=64, verbose_name='PDFハッシュ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='契約書送信日時')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_progress', to='core.partner', verbose_name='パートナー')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
            ],
            options={
                'verbose_name': '基本契約進捗',
                'verbose_name_plural': '基本契約進捗',
            },
        ),
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=4, verbose_name='銀行コード')),
                ('bank_name', models.CharField(max_length=128, verbose_name='銀行名')),
                ('branch_code', models.CharField(max_length=3, verbose_name='支店コード')),
                ('branch_name', models.CharField(max_length=128, verbose_name='支店名')),
            ],
            options={
                'verbose_name': '銀行マスタ',
                'verbose_name_plural': '銀行マスタ',
                'unique_together': {('bank_code', 'branch_code')},
            },
        ),
    ]
