# Generated by Django 6.0.1 on 2026-01-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerm',
            fields=[
                ('contract_term_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('deliverable_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('payment_term_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('workplace_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('order_end_ym', models.DateField()),
                ('order_date', models.DateField()),
                ('work_start', models.DateField()),
                ('work_end', models.DateField()),
                ('base_fee', models.IntegerField()),
                ('shortage_fee', models.IntegerField()),
                ('over_limit', models.IntegerField()),
                ('base_time', models.IntegerField()),
                ('contract_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contractterm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deliverable')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentterm')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
