# Generated by Django 6.0.1 on 2026-01-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contract_term',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliverable',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='order',
            name='project',
        ),
        migrations.RemoveField(
            model_name='order',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='person',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='取引先'),
        ),
        migrations.DeleteModel(
            name='ContractTerm',
        ),
        migrations.DeleteModel(
            name='Deliverable',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Workplace',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
