# Generated by Django 4.2.29 on 2026-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='contact_person',
            field=models.CharField(default='', max_length=64, verbose_name='連絡窓口担当者'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='社名'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(default='', max_length=10, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='registration_no',
            field=models.CharField(default='', max_length=20, verbose_name='登録番号'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='representative_name',
            field=models.CharField(default='', max_length=64, verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='responsible_person',
            field=models.CharField(default='', max_length=64, verbose_name='委託業務責任者'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tel',
            field=models.CharField(default='', max_length=20, verbose_name='電話番号'),
        ),
    ]
