# Generated by Django 4.2.28 on 2026-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_companyinfo_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_edi',
            field=models.BooleanField(default=False, help_text='EDIを保有している取引先は請求書の送付が不要', verbose_name='EDI保有'),
        ),
    ]
