# Generated by Django 6.0.1 on 2026-02-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_contract_term_remove_order_deliverable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='有限会社 マックプランニング', max_length=128, verbose_name='社名')),
                ('address', models.CharField(default='東京都荒川区東尾久8-9-14', max_length=255, verbose_name='住所')),
                ('tel', models.CharField(default='090-3043-0477', max_length=20, verbose_name='電話番号')),
                ('registration_no', models.CharField(default='TXXXXXXXXXXXXX', max_length=20, verbose_name='登録番号')),
            ],
            options={
                'verbose_name': '自社情報',
                'verbose_name_plural': '自社情報',
            },
        ),
    ]
