# Generated by Django 4.2.28 on 2026-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_has_edi'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='消費税率をパーセントで入力してください（例: 10.00）', max_digits=5, verbose_name='消費税率（%）'),
        ),
        migrations.AlterField(
            model_name='mastercontractprogress',
            name='status',
            field=models.CharField(choices=[('INVITED', '招待済み'), ('INFO_DONE', '基本情報登録済み'), ('CONTRACT_SENT', '基本契約送信済み'), ('PENDING_APPROVAL', '承諾待ち'), ('COMPLETED', '締結完了')], default='INVITED', max_length=20, verbose_name='ステータス'),
        ),
    ]
