# Generated by Django 6.0.1 on 2026-02-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='FAX番号'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='ロゴ画像'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(default='116-0012', max_length=10, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='representative_name',
            field=models.CharField(default='吉川 裕', max_length=64, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='representative_title',
            field=models.CharField(default='代表取締役', max_length=64, verbose_name='代表者役職'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name='印影画像'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='郵便番号'),
        ),
    ]
