# Generated by Django 4.2.29 on 2026-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyinfo_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='report_email',
            field=models.EmailField(blank=True, help_text='稼働報告メールの送信元アドレス（メインアドレスと異なる場合に設定）', max_length=254, verbose_name='報告用メールアドレス'),
        ),
    ]
