# Generated by Django 6.0.1 on 2026-02-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyinfo_fax_companyinfo_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
    ]
