# Generated by Django 4.2.28 on 2026-03-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='work_report_email',
            field=models.EmailField(blank=True, help_text='※稼働報告書（Excel）をメール自動送信する際の専用アドレスです。', max_length=254, verbose_name='稼働報告送付先メールアドレス'),
        ),
    ]
