# Generated by Django 4.2.28 on 2026-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_work_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_email',
            field=models.EmailField(blank=True, help_text='※未入力の場合は上の「メールアドレス」が請求書の送付等に利用されます。', max_length=254, verbose_name='請求書送付先メールアドレス'),
        ),
    ]
