# Generated by Django 6.0.1 on 2026-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyinfo_account_name_companyinfo_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='contact_person',
            field=models.CharField(default='吉川 裕', max_length=64, verbose_name='連絡窓口担当者'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='responsible_person',
            field=models.CharField(default='吉川 裕', max_length=64, verbose_name='委託業務責任者'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者'),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者'),
        ),
    ]
