# Generated by Django 4.2.29 on 2026-04-30 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_customer_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='default_from_email',
            field=models.EmailField(blank=True, help_text='メールの From に表示されるアドレス', max_length=254, verbose_name='送信元メールアドレス'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email_host',
            field=models.CharField(blank=True, help_text='例: smtp.gmail.com', max_length=255, verbose_name='SMTPホスト'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTPのアプリパスワード', max_length=255, verbose_name='SMTPパスワード'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP認証に使用するメールアドレス', max_length=255, verbose_name='SMTPユーザー'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email_port',
            field=models.IntegerField(blank=True, help_text='例: 587', null=True, verbose_name='SMTPポート'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS使用'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='staff_contact',
            field=models.ForeignKey(blank=True, help_text='支払通知・契約承認等の通知メール送信先となるスタッフ（「従業員」グループから選択）', limit_choices_to={'groups__name': '従業員'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partners', to=settings.AUTH_USER_MODEL, verbose_name='自社担当者'),
        ),
    ]
