# Generated by Django 6.0.1 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyinfo_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='口座名義'),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('普通', '普通'), ('当座', '当座')], default='普通', max_length=20, verbose_name='口座種別'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=64, verbose_name='支店名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='銀行名'),
        ),
    ]
