# Generated by Django 6.0.1 on 2026-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customer_account_name_customer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bcc',
            field=models.TextField(blank=True, help_text='複数指定する場合はカンマ区切りで入力してください', verbose_name='Bcc'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cc',
            field=models.TextField(blank=True, help_text='複数指定する場合はカンマ区切りで入力してください', verbose_name='Cc'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='FAX番号'),
        ),
    ]
