# Generated by Django 6.0.1 on 2026-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_bcc_customer_cc_customer_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_kana',
            field=models.CharField(blank=True, max_length=255, verbose_name='会社名（フリガナ）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_no',
            field=models.CharField(blank=True, help_text='T13桁の番号', max_length=20, verbose_name='登録番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='representative_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='representative_name_kana',
            field=models.CharField(blank=True, max_length=128, verbose_name='代表者名（フリガナ）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='representative_position',
            field=models.CharField(blank=True, max_length=64, verbose_name='代表者役職'),
        ),
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=4, verbose_name='銀行コード')),
                ('bank_name', models.CharField(max_length=128, verbose_name='銀行名')),
                ('branch_code', models.CharField(max_length=3, verbose_name='支店コード')),
                ('branch_name', models.CharField(max_length=128, verbose_name='支店名')),
            ],
            options={
                'verbose_name': '銀行マスタ',
                'verbose_name_plural': '銀行マスタ',
                'unique_together': {('bank_code', 'branch_code')},
            },
        ),
    ]
