# Generated by Django 6.0.1 on 2026-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer_name_kana_customer_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='customers/attachments/', verbose_name='添付書類（決算報告書等）'),
        ),
    ]
