# Generated by Django 6.0.1 on 2026-02-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customer_email_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContractProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', '招待済み'), ('INFO_DONE', '基本情報登録済み'), ('CONTRACT_SENT', '基本契約送信済み'), ('COMPLETED', '締結完了')], default='INVITED', max_length=20, verbose_name='ステータス')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_progress', to='core.customer', verbose_name='取引先')),
            ],
            options={
                'verbose_name': '基本契約進捗',
                'verbose_name_plural': '基本契約進捗',
            },
        ),
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.TextField(verbose_name='本文')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.customer', verbose_name='取引先')),
            ],
            options={
                'verbose_name': 'メール送信ログ',
                'verbose_name_plural': 'メール送信ログ',
                'ordering': ['-sent_at'],
            },
        ),
    ]
