# Generated by Django 4.2.28 on 2026-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mastercontractprogress_sentemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='システム内で識別するためのコード', max_length=50, unique=True, verbose_name='テンプレートコード')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.TextField(help_text='Djangoテンプレート構文が使用可能です。例: {{ partner_name }}', verbose_name='本文')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='説明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メールテンプレート',
                'verbose_name_plural': 'メールテンプレート',
            },
        ),
    ]
