# Generated by Django 4.2.28 on 2026-02-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'パートナー', 'verbose_name_plural': 'パートナー'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ユーザープロフィール', 'verbose_name_plural': 'ユーザープロフィール'},
        ),
    ]
