# Generated by Django 4.2.28 on 2026-02-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registration_no',
            field=models.CharField(blank=True, help_text='T13桁の番号', max_length=20, verbose_name='登録番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
