# Generated by Django 4.2.28 on 2026-02-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_client_registration_no_client_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='representative_title',
            field=models.CharField(blank=True, default='代表取締役', max_length=64, verbose_name='代表者役職'),
        ),
        migrations.AlterField(
            model_name='client',
            name='representative_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='代表者名'),
        ),
    ]
