# Generated by Django 4.2.28 on 2026-03-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_remaining_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercontractprogress',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='契約書PDF'),
        ),
        migrations.AddField(
            model_name='mastercontractprogress',
            name='pdf_hash',
            field=models.CharField(blank=True, help_text='SHA256ハッシュ値（電帳法対応）', max_length=64, verbose_name='PDFハッシュ'),
        ),
        migrations.AddField(
            model_name='mastercontractprogress',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='契約書送信日時'),
        ),
        migrations.AddField(
            model_name='mastercontractprogress',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日時'),
        ),
        migrations.AddField(
            model_name='mastercontractprogress',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='mastercontractprogress',
            name='status',
            field=models.CharField(choices=[('INVITED', '招待済み'), ('INFO_DONE', '基本情報登録済み'), ('CONTRACT_SENT', '基本契約送信済み'), ('PENDING_APPROVAL', '承認待ち'), ('COMPLETED', '締結完了')], default='INVITED', max_length=20, verbose_name='ステータス'),
        ),
    ]
