# Generated by Django 4.2.28 on 2026-03-12 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(help_text='YYMM+3桁連番 (例: 2602001)', max_length=20, unique=True, verbose_name='請求番号')),
                ('acceptance_no', models.CharField(blank=True, help_text='MP+請求番号', max_length=22, verbose_name='検収番号')),
                ('target_month', models.DateField(help_text='請求対象月', verbose_name='対象年月')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='作成日')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='検収日')),
                ('payment_deadline', models.DateField(blank=True, null=True, verbose_name='支払締切日')),
                ('payment_date', models.DateField(blank=True, help_text='実際に支払を行った日付', null=True, verbose_name='支払日')),
                ('department', models.CharField(blank=True, help_text='請求書に表示する部署名', max_length=128, verbose_name='部署名')),
                ('work_report_file', models.FileField(blank=True, help_text='Excel等の稼働報告書ファイル', null=True, upload_to='invoices/work_reports/', verbose_name='稼働報告書')),
                ('subtotal_amount', models.IntegerField(default=0, verbose_name='税抜合計')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='消費税')),
                ('total_amount', models.IntegerField(default=0, verbose_name='税込合計')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('PENDING_REVIEW', '確認待ち'), ('ISSUED', '発行済'), ('SENT', '送付済'), ('CONFIRMED', 'パートナー承認済'), ('PAID', '支払済')], default='DRAFT', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='注文')),
            ],
            options={
                'verbose_name': '請求・支払通知書',
                'verbose_name_plural': '請求・支払通知書',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=64, verbose_name='名前')),
                ('work_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='実稼働時間')),
                ('base_fee', models.IntegerField(default=0, verbose_name='単価/基本料金')),
                ('time_lower_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='基準時間_下限')),
                ('time_upper_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='基準時間_上限')),
                ('shortage_rate', models.IntegerField(default=0, verbose_name='不足単価')),
                ('excess_rate', models.IntegerField(default=0, verbose_name='超過単価')),
                ('excess_amount', models.IntegerField(default=0, verbose_name='超過金額')),
                ('shortage_amount', models.IntegerField(default=0, verbose_name='控除金額')),
                ('item_subtotal', models.IntegerField(default=0, verbose_name='金額（税抜）')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
            },
        ),
    ]
