# Generated by Django 6.0.1 on 2026-01-30 15:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_remove_order_base_time_remove_order_over_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(help_text='YYYYMM+3桁連番 (例: 2512006)', max_length=20, unique=True, verbose_name='請求番号')),
                ('acceptance_no', models.CharField(blank=True, help_text='MP+請求番号', max_length=22, verbose_name='検収番号')),
                ('target_month', models.DateField(help_text='請求対象月', verbose_name='対象年月')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='作成日')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='検収日')),
                ('payment_deadline', models.DateField(blank=True, null=True, verbose_name='支払締切日')),
                ('work_time', models.DecimalField(decimal_places=2, help_text='単位: 時間', max_digits=6, verbose_name='実稼働時間')),
                ('excess_amount', models.IntegerField(default=0, verbose_name='超過金額')),
                ('deduction_amount', models.IntegerField(default=0, verbose_name='控除金額')),
                ('subtotal_amount', models.IntegerField(default=0, verbose_name='税抜合計')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='消費税')),
                ('total_amount', models.IntegerField(default=0, verbose_name='税込合計')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('ISSUED', '発行済'), ('SENT', '送付済')], default='DRAFT', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='注文')),
            ],
        ),
    ]
