# Generated by Django 4.2.28 on 2026-03-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(blank=True, help_text='B列の日付データから自動検出', null=True, verbose_name='対象年月')),
                ('worker_name', models.CharField(blank=True, help_text='オートシェイプまたはファイル名から自動取得', max_length=128, verbose_name='作業者氏名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('file', models.FileField(upload_to='work_reports/', verbose_name='報告書ファイル')),
                ('original_filename', models.CharField(blank=True, max_length=512, verbose_name='元ファイル名')),
                ('status', models.CharField(choices=[('UPLOADED', '受領済'), ('PARSED', '解析済'), ('ALERT', '要確認'), ('APPROVED', '承認済'), ('ERROR', '解析エラー')], default='UPLOADED', max_length=20, verbose_name='ステータス')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='合計時間')),
                ('work_days', models.IntegerField(blank=True, null=True, verbose_name='稼働日数')),
                ('daily_data_json', models.JSONField(blank=True, help_text='[{"date": "2026-02-02", "hours": 8.0, "start": "9:00", "end": "18:00"}, ...]', null=True, verbose_name='日別データ')),
                ('alerts_json', models.JSONField(blank=True, help_text='[{"date": "2026-02-08", "type": "weekend", "hours": 8.0, "day_name": "土"}, ...]', null=True, verbose_name='警告データ')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='DriveファイルID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='orders.order', verbose_name='注文')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '稼働報告書',
                'verbose_name_plural': '稼働報告書',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
