# Generated by Django 4.2.28 on 2026-02-07 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '請求・支払通知書', 'verbose_name_plural': '請求・支払通知書'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='excess_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='work_time',
        ),
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.CharField(blank=True, help_text='請求書に表示する部署名', max_length=128, verbose_name='部署名'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(help_text='YYMM+3桁連番 (例: 2602001)', max_length=20, unique=True, verbose_name='請求番号'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=64, verbose_name='名前')),
                ('work_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='実稼働時間')),
                ('base_fee', models.IntegerField(default=0, verbose_name='単価/基本料金')),
                ('time_lower_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='基準時間_下限')),
                ('time_upper_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='基準時間_上限')),
                ('shortage_rate', models.IntegerField(default=0, verbose_name='不足単価')),
                ('excess_rate', models.IntegerField(default=0, verbose_name='超過単価')),
                ('excess_amount', models.IntegerField(default=0, verbose_name='超過金額')),
                ('shortage_amount', models.IntegerField(default=0, verbose_name='控除金額')),
                ('item_subtotal', models.IntegerField(default=0, verbose_name='金額（税抜）')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
            },
        ),
    ]
