# Generated by Django 4.2.28 on 2026-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_workreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('PENDING_REVIEW', '確認待ち'), ('ISSUED', '発行済'), ('SENT', '送付済'), ('CONFIRMED', 'パートナー承諾済'), ('PAID', '支払済')], default='DRAFT', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('UPLOADED', '受領済'), ('PARSED', '解析済'), ('ALERT', '要確認'), ('APPROVED', '確定済'), ('ERROR', '解析エラー')], default='UPLOADED', max_length=20, verbose_name='ステータス'),
        ),
    ]
