# Generated by Django 4.2.28 on 2026-02-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, help_text='実際に支払を行った日付', null=True, verbose_name='支払日'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_report_file',
            field=models.FileField(blank=True, help_text='Excel等の稼働報告書ファイル', null=True, upload_to='invoices/work_reports/', verbose_name='稼働報告書'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('ISSUED', '発行済'), ('SENT', '送付済'), ('CONFIRMED', 'パートナー確定済'), ('PAID', '支払済')], default='DRAFT', max_length=20, verbose_name='ステータス'),
        ),
    ]
