# Generated by Django 4.2.29 on 2026-03-31 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_report_email'),
        ('invoices', '0003_alter_invoice_status_alter_workreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512, unique=True, verbose_name='Message-ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='送信元')),
                ('from_name', models.CharField(blank=True, max_length=255, verbose_name='送信者名')),
                ('subject', models.CharField(max_length=512, verbose_name='件名')),
                ('received_at', models.DateTimeField(verbose_name='受信日時')),
                ('body_text', models.TextField(blank=True, verbose_name='本文')),
                ('status', models.CharField(choices=[('NEW', '新規'), ('IMPORTED', '取込済'), ('FORWARDED', '転送済'), ('IGNORED', '対象外'), ('ERROR', 'エラー')], default='NEW', max_length=20, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('attachment_filename', models.CharField(blank=True, max_length=512, verbose_name='添付ファイル名')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='received_emails/', verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to='core.partner', verbose_name='照合パートナー')),
                ('work_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='invoices.workreport', verbose_name='稼働報告書')),
            ],
            options={
                'verbose_name': '受信メール',
                'verbose_name_plural': '受信メール',
                'ordering': ['-received_at'],
            },
        ),
    ]
