# Generated by Django 4.2.28 on 2026-03-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_receivedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='client_shared_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='共有URL'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='sent_to_client_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送付日時'),
        ),
    ]
