# Generated by Django 4.2.29 on 2026-04-30 01:47

import core.services.encrypted_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_workreport_client_shared_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='自動生成された稼働報告PDFファイル', null=True, upload_to='work_reports/pdf/', verbose_name='PDFファイル'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='work_report_file',
            field=models.FileField(blank=True, help_text='Excel等の稼働報告書ファイル', null=True, storage=core.services.encrypted_storage.EncryptedFileSystemStorage(), upload_to='invoices/work_reports/', verbose_name='稼働報告書'),
        ),
        migrations.AlterField(
            model_name='receivedemail',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, storage=core.services.encrypted_storage.EncryptedFileSystemStorage(), upload_to='received_emails/', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='file',
            field=models.FileField(storage=core.services.encrypted_storage.EncryptedFileSystemStorage(), upload_to='work_reports/', verbose_name='報告書ファイル'),
        ),
    ]
