# Generated by Django 4.2.29 on 2026-04-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_remove_legacy_models'),
        ('invoices', '0006_add_pdf_file_to_workreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedemail',
            name='work_report',
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='monthly_timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='billing.monthlytimesheet', verbose_name='稼働報告'),
        ),
        migrations.DeleteModel(
            name='WorkReport',
        ),
    ]
