# Generated by Django 4.2.29 on 2026-03-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_initial_monthly_task'),
        ('core', '0004_customer_has_edi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_month', models.DateField(help_text='YYYY-MM-01形式', verbose_name='作業対象月')),
                ('task_type', models.CharField(choices=[('ORDER_CREATE', '注文書作成'), ('ORDER_APPROVE', '注文書承認'), ('REPORT_UPLOAD', '作業報告書アップロード'), ('INVOICE_CREATE', '請求書作成'), ('INVOICE_APPROVE', '請求書承認')], max_length=20, verbose_name='タスク種別')),
                ('responsible', models.CharField(choices=[('STAFF', '自社'), ('PARTNER', 'パートナー')], default='STAFF', max_length=10, verbose_name='担当区分')),
                ('deadline', models.DateField(verbose_name='期限日')),
                ('status', models.CharField(choices=[('PENDING', '未着手'), ('DONE', '完了'), ('OVERDUE', '期限超過')], default='PENDING', max_length=10, verbose_name='ステータス')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('note', models.TextField(blank=True, help_text='完了時の備考や関連情報', verbose_name='メモ')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='リマインド送信済み')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='アラート送信済み')),
                ('deadline_notified', models.BooleanField(default=False, verbose_name='期限到来通知済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tasks', to='core.partner', verbose_name='パートナー')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tasks', to='orders.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '月次タスク',
                'verbose_name_plural': '月次タスク',
                'ordering': ['deadline', 'task_type'],
                'unique_together': {('partner', 'project', 'work_month', 'task_type')},
            },
        ),
    ]
