# Generated by Django 4.2.28 on 2026-04-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercycle_order_cycle'),
        ('tasks', '0002_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytask',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.ordercycle', verbose_name='発注サイクル'),
        ),
    ]
