# Generated by Django 4.2.28 on 2026-03-28 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('SELF_ONLY', '自分のみ'), ('ALL', '全社員')], default='SELF_ONLY', max_length=10, verbose_name='権限レベル')),
                ('can_calculate', models.BooleanField(default=False, help_text='給与計算を実行できるか', verbose_name='計算実行権限')),
                ('can_approve', models.BooleanField(default=False, help_text='給与を確認済みにできるか', verbose_name='承認権限')),
                ('can_transfer', models.BooleanField(default=False, help_text='振込を実行できるか', verbose_name='振込実行権限')),
                ('employee', models.ForeignKey(blank=True, help_text='このユーザーに紐付く社員レコード', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.employee', verbose_name='紐付き社員')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_permission', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '給与権限',
                'verbose_name_plural': '給与権限',
            },
        ),
    ]
