# Generated by Django 4.2.28 on 2026-03-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='paid_leave_days',
            field=models.IntegerField(default=0, verbose_name='有給日数'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(blank=True, help_text='給与支給日', null=True, verbose_name='支給日'),
        ),
    ]
