# Generated by Django 4.2.28 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_paid_leave_days_payroll_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_1',
            field=models.CharField(blank=True, help_text='都道府県・市区町村・番地', max_length=200, verbose_name='住所1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_2',
            field=models.CharField(blank=True, help_text='建物名・部屋番号', max_length=200, verbose_name='住所2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='郵便番号'),
        ),
    ]
