# Generated by Django 4.2.28 on 2026-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employee_address_1_employee_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='社会保険加入日'),
        ),
    ]
