# Generated by Django 4.2.28 on 2026-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employee_insurance_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_day', models.IntegerField(choices=[(0, '月末'), (25, '25日'), (20, '20日'), (15, '15日'), (10, '10日')], default=0, help_text='0=月末、その他=指定日', verbose_name='支給日')),
                ('closing_day', models.IntegerField(choices=[(0, '月末'), (25, '25日'), (20, '20日'), (15, '15日')], default=0, help_text='0=月末締め', verbose_name='締め日')),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=1.25, help_text='法定: 1.25', max_digits=4, verbose_name='残業割増率')),
                ('overtime_60_rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='法定: 1.50', max_digits=4, verbose_name='60h超残業割増率')),
                ('night_rate_multiplier', models.DecimalField(decimal_places=2, default=0.25, help_text='法定: 0.25（基本給に加算）', max_digits=4, verbose_name='深夜割増率')),
                ('holiday_rate_multiplier', models.DecimalField(decimal_places=2, default=1.35, help_text='法定: 1.35', max_digits=4, verbose_name='休日出勤割増率')),
                ('default_work_days', models.IntegerField(default=20, help_text='勤怠データなし時に使用', verbose_name='デフォルト出勤日数')),
                ('default_monthly_hours', models.DecimalField(decimal_places=1, default=160.0, help_text='社員個別設定がない場合に使用', max_digits=5, verbose_name='デフォルト所定時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '給与設定',
                'verbose_name_plural': '給与設定',
            },
        ),
    ]
