# Generated by Django 4.2.29 on 2026-04-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_add_monthly_timesheet'),
        ('payroll', '0006_payrollsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.monthlytimesheet', verbose_name='勤怠報告'),
        ),
    ]
