# Generated by Django 6.0.1 on 2026-01-30 14:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_order_contract_term_remove_order_deliverable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerm',
            fields=[
                ('contract_term_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='契約条件ID')),
                ('description', models.CharField(max_length=255, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('deliverable_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='成果物ID')),
                ('description', models.CharField(max_length=255, verbose_name='成果物の内容')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('payment_term_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='支払条件ID')),
                ('description', models.CharField(max_length=255, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='プロジェクトID')),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('workplace_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='勤務場所ID')),
                ('name', models.CharField(max_length=100, verbose_name='勤務場所名')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(help_text='MP+YYYYMMDD+6桁連番', max_length=20, primary_key=True, serialize=False, verbose_name='注文番号')),
                ('status', models.CharField(choices=[('UNCONFIRMED', '未確認'), ('CONFIRMING', '確認中'), ('RECEIVED', '受領済')], default='UNCONFIRMED', max_length=20, verbose_name='ステータス')),
                ('order_end_ym', models.DateField(help_text='YYYY-MM-01形式など', verbose_name='注文終了年月')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='注文日')),
                ('work_start', models.DateField(verbose_name='作業開始日')),
                ('work_end', models.DateField(verbose_name='作業終了日')),
                ('base_fee', models.IntegerField(default=0, verbose_name='基本料金')),
                ('shortage_fee', models.IntegerField(default=0, verbose_name='不足単価')),
                ('over_limit', models.IntegerField(default=0, verbose_name='超過基準時間')),
                ('base_time', models.IntegerField(default=0, verbose_name='基準時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contractterm', verbose_name='契約条件')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='取引先')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.deliverable', verbose_name='成果物')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.paymentterm', verbose_name='支払条件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.project', verbose_name='プロジェクト')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.workplace', verbose_name='勤務場所')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='委託責任者、指揮命令者など', max_length=50, verbose_name='役割')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='連絡先')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='商品')),
            ],
        ),
    ]
