# Generated by Django 4.2.28 on 2026-03-12 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='パートナー')),
            ],
            options={
                'verbose_name': '契約条件',
                'verbose_name_plural': '契約条件',
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='成果物の内容')),
            ],
            options={
                'verbose_name': '成果物',
                'verbose_name_plural': '成果物',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(help_text='MP+YYYYMMDD+6桁連番', max_length=20, primary_key=True, serialize=False, verbose_name='注文番号')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('UNCONFIRMED', '未確認（発行済）'), ('CONFIRMING', '受領確認中'), ('RECEIVED', '受領済'), ('APPROVED', '承認済')], default='DRAFT', max_length=20, verbose_name='ステータス')),
                ('order_end_ym', models.DateField(help_text='YYYY-MM-01形式など', verbose_name='注文終了年月')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='注文日')),
                ('work_start', models.DateField(verbose_name='作業開始日')),
                ('work_end', models.DateField(verbose_name='作業終了日')),
                ('deliverable_text', models.CharField(default='月別作業報告書', max_length=255, verbose_name='納入物件（テキスト）')),
                ('payment_condition', models.TextField(blank=True, default='毎月末日締め翌月末日払い（税別）', help_text='PDFの支払条件欄に表示される詳細テキスト', verbose_name='詳細支払条件')),
                ('contract_items', models.TextField(blank=True, default='１．本作業に関わる著作権は、甲に一切帰属するものとする。\n２．乙は、本作業にて知り得た知識・企業秘密・ノウハウその他の情報（本作業自体を含め）、一切乙以外の外部に漏洩しないものとする。\n３．顧客の都合によりこの注文書の業務が中断もしくは終了した場合は、その時点で、当該注文は解除され発注の効力を失う。', help_text='PDF下部の契約条項', verbose_name='契約条項')),
                ('甲_責任者', models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者（甲）')),
                ('甲_担当者', models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者（甲）')),
                ('乙_責任者', models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者（乙）')),
                ('乙_担当者', models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者（乙）')),
                ('作業責任者', models.CharField(blank=True, max_length=64, verbose_name='作業責任者')),
                ('remarks', models.TextField(blank=True, help_text='口座情報など', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='正式発行または承認時のタイムスタンプ', null=True, verbose_name='確定日時')),
                ('document_hash', models.CharField(blank=True, help_text='改ざん防止用のハッシュ値', max_length=64, verbose_name='ドキュメントハッシュ')),
                ('order_pdf', models.FileField(blank=True, null=True, upload_to='orders/pdfs/', verbose_name='注文書PDF')),
                ('acceptance_pdf', models.FileField(blank=True, null=True, upload_to='acceptances/pdfs/', verbose_name='注文請書PDF')),
                ('external_signature_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='外部署名ID')),
                ('drive_file_id', models.CharField(blank=True, max_length=200, verbose_name='DriveファイルID')),
                ('contract_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contractterm', verbose_name='契約条件')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.deliverable', verbose_name='成果物')),
                ('partner', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='パートナー')),
            ],
            options={
                'verbose_name': '注文情報',
                'verbose_name_plural': '注文情報',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='勤務場所名')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
            ],
            options={
                'verbose_name': '勤務場所',
                'verbose_name_plural': '勤務場所',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='プロジェクトID')),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='取引先')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='委託責任者、指揮命令者など', max_length=50, verbose_name='役割')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='連絡先')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='orders.order')),
            ],
            options={
                'verbose_name': '担当者',
                'verbose_name_plural': '担当者',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='パートナー')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '支払条件',
                'verbose_name_plural': '支払条件',
                'unique_together': {('partner', 'project')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=64, verbose_name='作業者氏名')),
                ('effort', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='工数')),
                ('base_fee', models.IntegerField(default=0, verbose_name='月額基本料金')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='実稼働時間')),
                ('time_lower_limit', models.DecimalField(decimal_places=2, default=140.0, max_digits=5, verbose_name='基準時間_下限')),
                ('time_upper_limit', models.DecimalField(decimal_places=2, default=180.0, max_digits=5, verbose_name='基準時間_上限')),
                ('shortage_rate', models.IntegerField(default=0, verbose_name='不足単価')),
                ('excess_rate', models.IntegerField(default=0, verbose_name='超過単価')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.IntegerField(default=0, help_text='自動計算: (工数×基本料金) + 調整金', verbose_name='金額')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.paymentterm', verbose_name='支払条件'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.project', verbose_name='プロジェクト'),
        ),
        migrations.AddField(
            model_name='order',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.workplace', verbose_name='勤務場所'),
        ),
        migrations.AddField(
            model_name='contractterm',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.project', verbose_name='プロジェクト'),
        ),
        migrations.CreateModel(
            name='OrderBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_start_date', models.DateField(verbose_name='プロジェクト開始日')),
                ('project_end_date', models.DateField(verbose_name='プロジェクト終了日')),
                ('order_issuance_timing', models.CharField(choices=[('FIRST_DAY', '月初'), ('10TH_DAY', '10日'), ('15TH_DAY', '15日'), ('20TH_DAY', '20日'), ('LAST_DAY', '月末')], default='LAST_DAY', max_length=20, verbose_name='注文書発行タイミング')),
                ('invoice_issuance_timing', models.CharField(choices=[('FIRST_DAY', '月初'), ('10TH_DAY', '10日'), ('15TH_DAY', '15日'), ('20TH_DAY', '20日'), ('LAST_DAY', '月末')], default='LAST_DAY', max_length=20, verbose_name='請求書発行タイミング')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='パートナー')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '発注基本情報',
                'verbose_name_plural': '発注基本情報',
                'unique_together': {('partner', 'project')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contractterm',
            unique_together={('partner', 'project')},
        ),
    ]
