# Generated by Django 6.0.1 on 2026-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='base_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='over_limit',
        ),
        migrations.AddField(
            model_name='order',
            name='excess_fee',
            field=models.IntegerField(default=0, verbose_name='超過単価'),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, help_text='口座情報など', verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_lower_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='例: 140.00', max_digits=5, verbose_name='基準時間_下限'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_upper_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='例: 180.00', max_digits=5, verbose_name='基準時間_上限'),
        ),
    ]
