# Generated by Django 4.2.29 on 2026-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_monthly_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasicinfo',
            name='alert_days_after',
            field=models.IntegerField(default=3, help_text='期限超過何日後に自社担当者にアラートを送るか', verbose_name='アラート日数'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='invoice_approve_deadline_day',
            field=models.IntegerField(default=10, help_text='翌月の何日までにパートナーが請求書承認するか（例: 10 → 翌月10日）', verbose_name='請求書承認期限日（翌月）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='invoice_create_deadline_day',
            field=models.IntegerField(default=1, help_text='翌月の何日までに請求書を作成するか（例: 1 → 翌月1日）', verbose_name='請求書作成期限日（翌月）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='order_approve_deadline_days_before',
            field=models.IntegerField(default=0, help_text='前月末日から何日前が期限か（0=月末当日、1=月末1日前）', verbose_name='注文書承認期限（前月末からの日数）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='order_create_deadline_day',
            field=models.IntegerField(default=15, help_text='前月の何日までに注文書を作成するか（例: 15 → 前月15日）', verbose_name='注文書作成期限日（前月）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='パートナー担当タスクの期限何日前にリマインドメールを送るか', verbose_name='リマインド日数'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='report_upload_deadline_days_before',
            field=models.IntegerField(default=2, help_text='作業月末日から何日前が期限か（例: 2 → 月末2日前）', verbose_name='作業報告書期限（月末からの日数）'),
        ),
    ]
