# Generated by Django 6.0.1 on 2026-02-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_base_time_remove_order_over_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_items',
            field=models.TextField(blank=True, help_text='PDF下部の契約条項', verbose_name='契約条項'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliverable_text',
            field=models.CharField(default='月別作業報告書', max_length=255, verbose_name='納入物件（テキスト）'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_condition',
            field=models.TextField(blank=True, help_text='PDFの支払条件欄に表示される詳細テキスト', verbose_name='詳細支払条件'),
        ),
        migrations.AddField(
            model_name='order',
            name='乙_担当者',
            field=models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者（乙）'),
        ),
        migrations.AddField(
            model_name='order',
            name='乙_責任者',
            field=models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者（乙）'),
        ),
        migrations.AddField(
            model_name='order',
            name='作業責任者',
            field=models.CharField(blank=True, max_length=64, verbose_name='作業責任者'),
        ),
        migrations.AddField(
            model_name='order',
            name='甲_担当者',
            field=models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者（甲）'),
        ),
        migrations.AddField(
            model_name='order',
            name='甲_責任者',
            field=models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者（甲）'),
        ),
    ]
