# Generated by Django 6.0.1 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_contract_items_order_deliverable_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNCONFIRMED', '未確認'), ('CONFIRMING', '確認中'), ('RECEIVED', '受領済'), ('APPROVED', '承認済')], default='UNCONFIRMED', max_length=20, verbose_name='ステータス'),
        ),
    ]
