# Generated by Django 4.2.29 on 2026-03-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_deadline_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasicinfo',
            name='contract_items',
            field=models.TextField(blank=True, default='１．本作業に関わる著作権は、甲に一切帰属するものとする。\n２．乙は、本作業にて知り得た知識・企業秘密・ノウハウその他の情報（本作業自体を含め）、一切乙以外の外部に漏洩しないものとする。\n３．顧客の都合によりこの注文書の業務が中断もしくは終了した場合は、その時点で、当該注文は解除され発注の効力を失う。', verbose_name='契約条項'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='deliverable_text',
            field=models.CharField(blank=True, default='月別作業報告書', max_length=255, verbose_name='納入物件'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='payment_condition',
            field=models.TextField(blank=True, default='毎月末日締め翌月末日払い（税別）', verbose_name='支払条件'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workplace', verbose_name='勤務場所'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='乙_担当者',
            field=models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者（乙）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='乙_責任者',
            field=models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者（乙）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='作業責任者',
            field=models.CharField(blank=True, max_length=64, verbose_name='作業責任者'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='甲_担当者',
            field=models.CharField(blank=True, max_length=64, verbose_name='連絡窓口担当者（甲）'),
        ),
        migrations.AddField(
            model_name='orderbasicinfo',
            name='甲_責任者',
            field=models.CharField(blank=True, max_length=64, verbose_name='委託業務責任者（甲）'),
        ),
        migrations.CreateModel(
            name='OrderBasicInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=64, verbose_name='作業者氏名')),
                ('effort', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='工数')),
                ('base_fee', models.IntegerField(default=0, verbose_name='月額基本料金')),
                ('time_lower_limit', models.DecimalField(decimal_places=2, default=140.0, max_digits=5, verbose_name='基準時間_下限')),
                ('time_upper_limit', models.DecimalField(decimal_places=2, default=180.0, max_digits=5, verbose_name='基準時間_上限')),
                ('shortage_rate', models.IntegerField(default=0, verbose_name='不足単価')),
                ('excess_rate', models.IntegerField(default=0, verbose_name='超過単価')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='orders.orderbasicinfo', verbose_name='発注基本情報')),
            ],
            options={
                'verbose_name': '基本情報明細テンプレート',
                'verbose_name_plural': '基本情報明細テンプレート',
            },
        ),
    ]
