# Generated by Django 4.2.29 on 2026-03-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_basicinfo_template_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyTask',
        ),
    ]
