# Generated by Django 6.0.1 on 2026-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_hash',
            field=models.CharField(blank=True, help_text='改ざん防止用のハッシュ値', max_length=64, verbose_name='ドキュメントハッシュ'),
        ),
        migrations.AddField(
            model_name='order',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='正式発行または承認時のタイムスタンプ', null=True, verbose_name='確定日時'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('UNCONFIRMED', '未確認（発行済）'), ('CONFIRMING', '受領確認中'), ('RECEIVED', '受領済'), ('APPROVED', '承認済')], default='UNCONFIRMED', max_length=20, verbose_name='ステータス'),
        ),
    ]
