# Generated by Django 4.2.28 on 2026-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_initial_monthly_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('UNCONFIRMED', '未確認（発行済）'), ('CONFIRMING', '受領確認中'), ('RECEIVED', '受領済'), ('APPROVED', '承諾済')], default='DRAFT', max_length=20, verbose_name='ステータス'),
        ),
    ]
