# Generated by Django 6.0.1 on 2026-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_document_hash_order_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance_pdf',
            field=models.FileField(blank=True, null=True, upload_to='acceptances/pdfs/', verbose_name='注文請書PDF'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(blank=True, null=True, upload_to='orders/pdfs/', verbose_name='注文書PDF'),
        ),
    ]
