# Generated by Django 4.2.28 on 2026-04-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_invoice_email'),
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_month', models.DateField(help_text='YYYY-MM-01形式', verbose_name='作業対象月')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cycles', to='core.partner', verbose_name='パートナー')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cycles', to='orders.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '月次発注サイクル',
                'verbose_name_plural': '月次発注サイクル',
                'ordering': ['-work_month', 'partner', 'project'],
                'unique_together': {('partner', 'project', 'work_month')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.ordercycle', verbose_name='発注サイクル'),
        ),
    ]
