# Generated by Django 6.0.1 on 2026-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_external_signature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('UNCONFIRMED', '未確認（発行済）'), ('CONFIRMING', '受領確認中'), ('RECEIVED', '受領済'), ('APPROVED', '承認済')], default='DRAFT', max_length=20, verbose_name='ステータス'),
        ),
    ]
