# Generated by Django 4.2.28 on 2026-04-24 00:13

from django.db import migrations


def populate_order_cycles(apps, schema_editor):
    """
    既存の MonthlyTask / Order からOrderCycleレコードを生成し、FKを紐付ける。
    """
    OrderCycle = apps.get_model('orders', 'OrderCycle')
    MonthlyTask = apps.get_model('tasks', 'MonthlyTask')
    Order = apps.get_model('orders', 'Order')

    # 1. MonthlyTask の (partner, project, work_month) から OrderCycle を生成
    task_groups = (
        MonthlyTask.objects
        .values_list('partner_id', 'project_id', 'work_month')
        .distinct()
    )
    cycle_cache = {}
    for partner_id, project_id, work_month in task_groups:
        cycle, _ = OrderCycle.objects.get_or_create(
            partner_id=partner_id,
            project_id=project_id,
            work_month=work_month,
        )
        cycle_cache[(partner_id, project_id, work_month)] = cycle

    # 2. 各 MonthlyTask に cycle をセット
    for task in MonthlyTask.objects.all():
        key = (task.partner_id, task.project_id, task.work_month)
        if key in cycle_cache:
            task.cycle = cycle_cache[key]
            task.save(update_fields=['cycle'])

    # 3. 各 Order に cycle をセット（partner + project + order_end_ym で照合）
    for order in Order.objects.all():
        key = (order.partner_id, order.project_id, order.order_end_ym)
        if key in cycle_cache:
            order.cycle = cycle_cache[key]
            order.save(update_fields=['cycle'])
        else:
            # order_end_ym が月末日の場合、月初に変換して照合
            month_start = order.order_end_ym.replace(day=1)
            key2 = (order.partner_id, order.project_id, month_start)
            if key2 in cycle_cache:
                order.cycle = cycle_cache[key2]
                order.save(update_fields=['cycle'])


def reverse_populate(apps, schema_editor):
    """逆マイグレーション: cycle FK をクリア"""
    MonthlyTask = apps.get_model('tasks', 'MonthlyTask')
    Order = apps.get_model('orders', 'Order')
    MonthlyTask.objects.all().update(cycle=None)
    Order.objects.all().update(cycle=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercycle_order_cycle'),
        ('tasks', '0003_monthlytask_cycle'),
    ]

    operations = [
        migrations.RunPython(populate_order_cycles, reverse_populate),
    ]
