# Generated by Django 4.2.28 on 2026-04-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_populate_order_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercycle',
            name='payment_completed',
            field=models.BooleanField(default=False, help_text='Invoiceが存在しない場合でも手動で支払完了をマークできる', verbose_name='支払完了'),
        ),
        migrations.AddField(
            model_name='ordercycle',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支払完了日時'),
        ),
    ]
