# Generated by Django 4.2.28 on 2026-02-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customer_options_alter_profile_options'),
        ('orders', '0009_alter_orderitem_id_alter_person_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractterm',
            options={'verbose_name': '契約条件', 'verbose_name_plural': '契約条件'},
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'verbose_name': '成果物', 'verbose_name_plural': '成果物'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文情報', 'verbose_name_plural': '注文情報'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '注文明細', 'verbose_name_plural': '注文明細'},
        ),
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'verbose_name': '支払条件', 'verbose_name_plural': '支払条件'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '担当者', 'verbose_name_plural': '担当者'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'プロジェクト', 'verbose_name_plural': 'プロジェクト'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': '勤務場所', 'verbose_name_plural': '勤務場所'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OrderBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_start_date', models.DateField(verbose_name='プロジェクト開始日')),
                ('project_end_date', models.DateField(verbose_name='プロジェクト終了日')),
                ('order_issuance_timing', models.CharField(choices=[('FIRST_DAY', '月初'), ('10TH_DAY', '10日'), ('15TH_DAY', '15日'), ('20TH_DAY', '20日'), ('LAST_DAY', '月末')], default='LAST_DAY', max_length=20, verbose_name='注文書発行タイミング')),
                ('invoice_issuance_timing', models.CharField(choices=[('FIRST_DAY', '月初'), ('10TH_DAY', '10日'), ('15TH_DAY', '15日'), ('20TH_DAY', '20日'), ('LAST_DAY', '月末')], default='LAST_DAY', max_length=20, verbose_name='請求書発行タイミング')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='取引先')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '発注基本情報',
                'verbose_name_plural': '発注基本情報',
                'unique_together': {('customer', 'project')},
            },
        ),
    ]
