# Generated by Django 4.2.28 on 2026-04-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordercycle_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterm',
            name='closing_day',
            field=models.IntegerField(choices=[(15, '15日締め'), (20, '20日締め'), (25, '25日締め'), (0, '月末締め')], default=0, help_text='0=月末', verbose_name='締め日'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='payment_day',
            field=models.IntegerField(choices=[(10, '10日払い'), (15, '15日払い'), (20, '20日払い'), (25, '25日払い'), (0, '末日払い')], default=0, help_text='0=末日', verbose_name='支払日'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='payment_month_offset',
            field=models.IntegerField(choices=[(0, '当月'), (1, '翌月'), (2, '翌々月')], default=1, help_text='締め月から何ヶ月後に支払うか', verbose_name='支払月'),
        ),
    ]
