# Generated by Django 4.2.28 on 2026-02-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_contractterm_options_alter_deliverable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='実稼働時間'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_fee',
            field=models.IntegerField(default=0, verbose_name='月額基本料金'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='effort',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='工数'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='excess_rate',
            field=models.IntegerField(default=0, verbose_name='超過単価'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='person_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='作業者氏名'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shortage_rate',
            field=models.IntegerField(default=0, verbose_name='不足単価'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='time_lower_limit',
            field=models.DecimalField(decimal_places=2, default=140.0, max_digits=5, verbose_name='基準時間_下限'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='time_upper_limit',
            field=models.DecimalField(decimal_places=2, default=180.0, max_digits=5, verbose_name='基準時間_上限'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0, help_text='自動計算: (工数×基本料金) + 調整金', verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='商品'),
        ),
    ]
