# Generated by Django 4.2.28 on 2026-02-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_client_representative_title_and_more'),
        ('orders', '0016_payment_contract_client_partner_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbasicinfo',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='パートナー'),
        ),
    ]
