# Generated by Django 4.2.28 on 2026-02-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderbasicinfo_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='DriveファイルID'),
        ),
    ]
