# Generated by Django 4.2.28 on 2026-02-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_partner_db_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='partner',
        ),
    ]
