# Generated by Django 4.2.28 on 2026-03-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_order_customer_remove_person_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='base_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='excess_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shortage_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_lower_limit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_upper_limit',
        ),
    ]
